[project]
name = "55-flask-advanced-forms"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "Bootstrap-Flask==2.2.0",
    "Flask==2.3.2",
    "WTForms==3.0.1",
    "Flask-WTF==1.2.1",
    "Werkzeug==3.0.0",
]